### ISSUE TITLE
Support for community towers 

### ISSUE THREAD

**Issue by froehlichA** [olistic/warriorjs#100]
Currently, only the beginner tower is supported in the game. To add other towers, one has to manually rewrite the source code [like shown here](https://spectrum.chat/thread/65415831-132a-4c15-8c75-848d941daffe).

Maybe the cli could scan for node modules beginning with ``warriorjs-tower-`` in the ``warriorjs`` directory and try to load the respective towers.

**Comment by olistic** [comment]
This is something I was going to work on after finishing the documentation for tower makers (currently in progress). But please feel free to expand on this idea, I like it.
