### ISSUE TITLE
Warrior should be upset when losing points

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#104]
Currently, the warrior [is proud of earning points](https://github.com/olistic/warriorjs/blob/fbc5c10c30124f45bb876a6ef2a5a6d59ec36436/packages/warriorjs-core/src/Warrior.js#L37-L40), but he or she should also be upset for losing points.

**Comment by skywalker212** [comment]
can i work on this?
I have to modify the losePoints method, right?

**Comment by olistic** [comment]
Hey @skywalker212, of course! Units can earn or lose points, but they do so silently. In case of the warrior, we want to log that using `.say()`. We are already doing that for `earnPoints` [here](https://github.com/olistic/warriorjs/blob/fbc5c10c30124f45bb876a6ef2a5a6d59ec36436/packages/warriorjs-core/src/Warrior.js#L37-L40). Now we need to do the same for `losePoints` (override its implementation in `Warrior`).

**Comment by skywalker212** [comment]
okay!

**Comment by skywalker212** [comment]
https://github.com/skywalker212/warriorjs/commit/f6fcd253d3cdf8d35353b90577a437501228e696
@olistic please review.

**Comment by olistic** [comment]
@skywalker212 Looks good, you should open a PR for review though!

**Comment by skywalker212** [comment]
@olistic okay!
