### ISSUE TITLE
Mobile browser based version possible?

### ISSUE THREAD

**Issue by RetroGamer547** [olistic/warriorjs#110]
I would like to request a browser based version for mobile because I currently can’t play.  Would this even be possible?  It also should help the game expand further beyond github and product hunt.

Happy coding! -Retro

**Comment by RetroGamer547** [comment]
Perhaps with its own little website like Paperclips or Kittens?

**Comment by olistic** [comment]
Hello @RetroGamer547! A web version of the game is in the works, will be available at [warriorjs.com](https://warriorjs.com). Stay tuned!

**Comment by RetroGamer547** [comment]
Awesome! Thanks :)

**Comment by RetroGamer547** [comment]
Does this website belong to you? http://jswarrior.fusioncharts.com/

-Nathan

**Comment by RetroGamer547** [comment]
Huh. Ok

-Nathan
