### ISSUE TITLE
Diamond character in score is broken on Windows CMD

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#112]
# Environment

## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
 - Memory: 4.47 GB / 7.88 GB
## Binaries:
 - npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

# Steps to reproduce

Run any level of WarriorJS in Windows' CMD.

# Expected Behavior

Warrior status shows a diamond character for the score.

# Actual Behavior

Warrior status shows an unrecognized character symbol for the score.

# Screenshots

![bug](https://user-images.githubusercontent.com/5600126/40126618-1390207c-5904-11e8-8f76-6b85270bb186.png)

**Comment by olistic** [comment]
♦ (_Black Diamond Suit_ in the Miscellaneous Symbols unicode block) is a safe alternative for the currently used ⬥ (_Black Medium Diamond_).

**Comment by olistic** [comment]
Hey @Eveneit, I saw you fixed this when troubleshooting #111. Would you like to submit a PR?

**Comment by glneto** [comment]
@olistic do you want that changed for every OS or do you want to keep the Black Medium Diamond for non-windows OS?
