### ISSUE TITLE
Unable to detect the direction you are taking damage from.

### ISSUE THREAD

**Issue by pigalot** [olistic/warriorjs#124]
I propose adding a function to the player API to check what body part has an arrow sticking out of it or has been burnt by magic.

Currently to complete the beginner tower you need to make assumptions on the direction of the most lethal enemies. Currently adding an extra level and swapping two enemies would make epic near impossible.

**Comment by olistic** [comment]
Hello @pigalot! Thanks for your input on this. I'm moving this comment to #103 and closing this issue. Let's have the discussion there.
