### ISSUE TITLE
Feature request: Regression tests on each new run

### ISSUE THREAD

**Issue by JayAndCatchFire** [olistic/warriorjs#127]
I don't necessarily assume this is the case for all players of the game, but as I develop my AI "player" I'm intending on building up an expert system that can handle any level in the domain of how a level is defined. Each new level (in the first tower at least) expands the level domain over the previous level.

However, one could theoretically write a "player" on each level that can only handle the current level specifically. 

I'm currently on level 8 of the first tower. I have a sneaking suspicion that my current "player" would technically fail one of the earlier levels.

Wouldn't it be nice if you could run your player on the current level and all previous levels of the tower? Also, it would be interesting to see if a recent change improves or hurts your previous levels' scores.

**Comment by olistic** [comment]
That's more or less what the [epic mode](https://warrior.js.org/docs/epic-mode) is about. You'll have the option to enable epic mode once you reach to the top of the tower (you have one more level to go).

**Comment by olistic** [comment]
I'm closing this issue, feel free to re-open if epic mode doesn't enable everything you meant!
