### ISSUE TITLE
Readme doesn't mention getUnit on level 5

### ISSUE THREAD

**Issue by glneto** [olistic/warriorjs#136]
Hello!

I was on level 5 and took me a while to discover how to get the unit. On the readme file it says:

> "Once you find a unit, use `unit.isFriendly() && unit.isBound()` to see if there's a captive and `warrior.rescue()` to rescue him. Don't attack captives."

But it doesn't mention the use of the warrior.feel().getUnit() for that.

I was thinking that this could be a point where people quit the game, trying to use `unit.isFriendly` and receiving a `not defined` error.

Is the player supposed to figure that out or can the readme file be improved?

**Comment by olistic** [comment]
I literally just merged #135, which enhances the docs. Should be deployed in a few mins!
