### ISSUE TITLE
How to get past level 9?

### ISSUE THREAD

**Issue by apikurious** [olistic/warriorjs#15]
I know this is supposed to make you learn... But I have been trying for 6 hours and I still cannot get past this stage. So I figured this is possibly the best my brain can do with the limited experience I have with javascript.

Firstly, I don't know what is the attack range of the wizards.
Secondly, I also don't know how to use the .look() ability.
But after fiddling with them a bit, I realized that the look ability actually returns an array. However there's no way to use that unless you put what is returned into another variable to be read as an array.
And after doing that, I am guessing I would have to loop through the items or something and I did that but my warrior either does nothing, or walks forward, saves captive, walks forward, attacks the wizard, rests and gets killed by the second wizard. I have tried to check if the position of the wizard is at least 3 spots away from my warrior and to move backward if it isn't but because of the second wizard, the for loop just uses the second wizard to account for position...

so how do I solve this..? Am I overthinking this?!

**Comment by olistic** [comment]
You managed to get to level 9, so I'm sure your brain works pretty well! My recommendation: take a look at the source code, look at how the wizard's (and archer's) turn is played. The `look` ability returns an array containing the first three spaces in the given direction, so you can call any `Space` method on them, as you have done till now with `feel`.

When you start using abilities that return arrays, you should be familiar with the [methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) that can be called on an Array. You will find many of them useful (remember you can use the ES6 methods too). Here is an example:

```javascript
class Player {
   // ...

  isEnemyInSight(warrior) {
    return warrior.look().findIndex((space) => space.isEnemy()) !== -1;
  }
}
```

Good luck!

**Comment by Lichtjaeger** [comment]
You use ES2015 (ES6) in warriorjs. So why not use ES5 methods?
A better way for this example is to use [Array.some()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) instead of Array.findIndex().

**Comment by olistic** [comment]
I wanted to illustrate the possibility of using ES6 methods, like [Array.prototype.findIndex()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex). But yes, I agree with you on that [Array.prototype.some()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) would be better for this case.

This would be even better, because it will check that the unit is the first in sight, besides being an enemy:
```javascript
isEnemyInSight(warrior) {
  const unit = warrior.look().find((space) => !space.isEmpty());
  return unit && unit.isEnemy();
}
```
