### ISSUE TITLE
Feature request: clearer display

### ISSUE THREAD

**Issue by Offirmo** [olistic/warriorjs#153]
Playing the game, I found out that the stats and map displayed in previous terminal lines are updated after the turn.

This makes the output hard to read, because we can't assume that terminal lines content is ordered like a timeline. This is no longer a "history".

See an example:
<img width="431" alt="screen shot 2018-05-22 at 18 12 52" src="https://user-images.githubusercontent.com/603503/40396353-ea726166-5e6f-11e8-9f77-b63242da2a50.png">

1. status displays health = 20
1. my character "my health is 20/20"
1. a sludge attack me
1. I have now 17 HP **AND the health display above is updated to 17**
1. On the next status display, we see "14", would have expected 17

The same for the map.

I would suggest NOT updating past terminal lines, thus having a clear, time-ordered line-by-line history.

**Comment by pigalot** [comment]
The display is a summary of the turn:

- Health at end of turn.
- Points at end of turn.
- Position.
- Event log.

As a note the turns are all taken at once and then the output is done from the results after the fact.

**Comment by olistic** [comment]
@Offirmo The current behavior strikes a balance between too much information (the floor map being printer on every action), and lack of information (a single floor map for the entire play log). I tested those other alternatives and they weren't convincing. What I would be interested in doing, however, is what's presented in #155.
