### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#155]
The proposal is to use [blessed](http://blessedjs.org) for a revamped UI. This will probably allow lots of improvements, but the main motivation for the change would be a better play log:

![untitled](https://user-images.githubusercontent.com/5600126/40428122-fe3c0fde-5e75-11e8-9334-5553dbcf0f11.png)

## Requirements

- [ ] Print level header (`~~~ level 4 ~~~` in the example) in the first row of the screen, fixed.
- [ ] Print warrior status (life and score) and floor map below the header, also fixed. The status and the map will be re-rendered whenever they change.
- [ ] Print play log below the fixed elements, in a scrollable section filling the rest of the screen.
- [ ] The play log automatically scrolls down when the log grows bigger than the terminal size, always following the play.
- [ ] In epic mode, between level and level, the old play is cleared and the new level takes its place. The player can always use the `--level` CLI option to only play one level and analyze the output.

## Not for now

* Changing the dialogs before and after the playback.
* Step by step playback. I envision this being a possibility, with play, pause, step back and step forward functions, but let's leave it for a future PR.

Feedback?

**Comment by jeroenrinzema** [comment]
If you want can I start working on this.

**Comment by olistic** [comment]
@jeroenrinzema Sure, that'd be awesome! I updated the description so you can have a better idea. Let me know if you still want to do it and I'll mark this as claimed. Thanks!

**Comment by jeroenrinzema** [comment]
I have build this so far in a small prototyping env. What do you think?

![screen shot 2018-05-25 at 15 52 23](https://user-images.githubusercontent.com/3440116/40547984-afa224a2-6033-11e8-8c23-6aa96c5a90e3.png)

**Comment by olistic** [comment]
@jeroenrinzema That's beautiful!

I wonder if it would visually separate the elements better if we print a separator row (`printSeparator()` function) at the end of the fixed section:

```
~~~~~~~~~~ level 1 ~~~~~~~~~~
♥ 20
♦ 0
╔══════╗
║@    >║
╚══════╝
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   <-- New separator row
<LOG STARTS HERE>
```

What do you think?

**Comment by jeroenrinzema** [comment]
Looks good! I will implement it.

**Comment by olistic** [comment]
@jeroenrinzema 

> Just for clarification do you want to use the current UI layout in epic mode?

No, also the new one. Currently, epic mode prints one level after the other:

<img width="778" alt="screen shot 2018-05-25 at 10 46 25" src="https://user-images.githubusercontent.com/5600126/40547710-0487e162-6009-11e8-9b72-01d584769037.png">

^ _Finishing level 8 and starting level 9 right after it._

Now, with blessed you will create a screen that will fill the entire terminal, right? So when one level ends and the next level starts, where do you print the new level? You could:

a. Abandon the current blessed screen, leaving the contents printed in the terminal and creating a new screen for the new level, which would then result in an output similar to what we currently have (I would prefer this option, but I don't know if it's possible).
b. Clear the current blessed elements (level header, status, floor map and log) and re-use them to print the new level. This is what I meant when I said _"In epic mode, between level and level, the old play is cleared and the new level takes its place"_ in the description.
c. Other options?

**Comment by jeroenrinzema** [comment]
@olistic I was thinking about option `A` this should automatically work since I am constructing the level layout in the `Game.js@playLevel(levelNumber)` method

**Comment by olistic** [comment]
@jeroenrinzema Perfect!!!

**Comment by jeroenrinzema** [comment]
I got a beta version of the [new UI](https://github.com/jeroenrinzema/warriorjs) that is ready to be tested. I still need to write documentation and tests and clean up the code here and there.
