### ISSUE TITLE
Add an advanced tower

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#16]

**Comment by matita** [comment]
Yes, please

**Comment by david-gang** [comment]
Would like to have two dimensional levels

**Comment by olistic** [comment]
@david-gang The intermediate tower already adds two-dimensional levels. I was thinking on creating a new `Space` type, something like a pit of spikes, that is walkable (meaning you don't bounce like when you walk against walls) but if you do, you instantly die. Of course there will be also new abilities and units.

Any idea is more than welcome!
