### ISSUE TITLE
Enhance "look" ability

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#160]
Right now, the ["look" ability](https://github.com/olistic/warriorjs/blob/405d7c205172d152a73573062d9313baeec1716e/packages/warriorjs-abilities/src/look.js) always returns the first three spaces in the given direction.

In this situation (warrior facing west):

```
╔══════╗
║@    >║
╚══════╝
```

`warrior.look()` would return `[wall, wall, wall]` (`wall` is actually a space with `isWall() === true`). It would be better if "look" stopped at the first wall, returning just `[wall]` in this case.

**Comment by pigalot** [comment]
I would like to give this one a go if that alright.
