### ISSUE TITLE
docs/towers.html page is dead.

### ISSUE THREAD

**Issue by hasparus** [olistic/warriorjs#168]
Readme is linking to https://warrior.js.org/docs/towers.html

## 🤔 Expected Behavior
There is a page in the docs clarifying that there is only one tower and encouraging contribution.

## 😯 Actual Behavior
404

**Comment by nukeop** [comment]
Still dead unfortunately.

**Comment by olistic** [comment]
Hello @nukeop, README now points to https://warrior.js.org/docs/play/towers, which should work.

**Comment by nukeop** [comment]
Right, I was thinking about a different link.

https://warrior.js.org/docs/en/play/towers

The "add it" link points to a file that no longer exists.

**Comment by olistic** [comment]
@nukeop Ugh, sorry for that. It should be fixed now, thanks!
