### ISSUE TITLE
ES6ness: use `export class Player` instead of `global.Player = Player`

### ISSUE THREAD

**Issue by PandaWhisperer** [olistic/warriorjs#17]
Hey, just found your game through Twitter, neat idea! Wish I'd though of it...

Anyways, great to see it's ES6 ready. However, instead of using a global variable, the player code should probably [export the `Player` class instead](https://github.com/lukehoban/es6features#modules).

Otherwise, keep up the good work!

**Comment by olistic** [comment]
Thanks for the kind words. I ended up by refactoring it in a way it doesn't require any of them.
