### ISSUE TITLE
Sort abilities alphabetically in profile's README

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#189]
Abilities should be sorted alphabetically under the sections "Actions" and "Senses" of the profile's README.

**Comment by djohalo2** [comment]
@olistic Looks like a good issue to start with! However, after cloning the repo, running the necessary yarn installs, I can't seem to get my local version running to test changes. Whenever I run the warriorjs.js from the cli package with node I get unhandled promise rejections :/ Did I miss some steps perhaps?

**Comment by olistic** [comment]
Hello @djohalo2, and thanks for your interest in the project! Would you mind opening a new issue and completing the issue template so I can help you better?

**Comment by olistic** [comment]
@djohalo2 Before opening the issue, give it another try. It could have been fixed by e790005.

**Comment by djohalo2** [comment]
@olistic It works now! I will then pick up this issue, it that's alright!
