### ISSUE TITLE
rest() method doesn't update health();

### ISSUE THREAD

**Issue by ShintoTuna** [olistic/warriorjs#19]
It seems that rest() method doesn't update health in current round;

if my current health is 15 and I'm doing

console.log(warrior.health());
warrior.rest();
console.log(warrior.health());

I'm getting both console logs 15.

Is this intended or am i missing something?

**Comment by olistic** [comment]
When the `playTurn` method is executed, it *sets* the action to be performed in this turn, but it is not until the `performTurn` method (an internal method) is called that the action takes place. For that reason, you won't see any change in your health during the `playTurn` method. It will take place later :).
