### ISSUE TITLE
warriorjs: command not found

### ISSUE THREAD

**Issue by oronbz** [olistic/warriorjs#2]
After successfully installing warriorjs with:
````
npm install -g warriorjs
````
i'm getting
````
-bash: warriorjs: command not found
````

This isn't the first global module that I install btw (:

**Comment by olistic** [comment]
It seems that your installation of node/npm is putting npm binaries in a place that is not in the path. This usually happens with homebrew installations of node, if that's the case. Could you please paste what you get after running:

```bash
npm install -g warriorjs
```

**Comment by oronbz** [comment]
Again, this is not the first time I install and use global package, an i'm able to use other global modules just fine but there you go:
````
Last login: Sat May 16 15:53:54 on ttys001
Orons-MacBook-Pro:~ oron$ npm install -g warriorjs

> sleep@2.0.0 install /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/warriorjs/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/node_sleep.node
  SOLINK_MODULE(target) Release/node_sleep.node: Finished

> fsevents@0.3.6 install /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/warriorjs/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
/usr/local/Cellar/node/0.12.2_1/libexec/npm/bin/warriorjs -> /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/warriorjs/bin/warriorjs
warriorjs@0.1.6 /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/warriorjs
├── readline-sync@1.2.15
├── ejs@2.3.1
├── lodash@3.8.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── glob@5.0.6 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.7)
├── fs-extra@0.18.3 (jsonfile@2.0.0, graceful-fs@3.0.6, rimraf@2.3.3)
├── sleep@2.0.0 (nan@1.8.4)
├── yargs@3.9.0 (decamelize@1.0.0, camelcase@1.1.0, window-size@0.1.0, cliui@2.1.0)
└── babel@5.4.3 (slash@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.1, convert-source-map@1.1.0, commander@2.8.1, source-map@0.4.2, output-file-sync@1.1.0, babel-core@5.4.3, chokidar@1.0.1)
Orons-MacBook-Pro:~ oron$ warriorjs
-bash: warriorjs: command not found
````

**Comment by olistic** [comment]
With "use" you mean CLIs? Because it might not be the first time you install and use a global package, but maybe it's the first with a binary. Sorry I'm being insistent, I just want to clear out the possibility before moving on to anything else.

You are getting this:

```
/usr/local/Cellar/node/0.12.2_1/libexec/npm/bin/warriorjs -> /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/warriorjs/bin/warriorjs
```

which means that `/usr/local/Cellar/node/0.12.2_1/libexec/npm/bin` must be on your path to be able to run `warriorjs` command from anywhere. What do you get if you run:

```bash
$ echo $PATH
```

**Comment by oronbz** [comment]
Whe running /usr/local/Cellar/node/0.12.2_1/libexec/npm/bin/warriorjs it is working, so I guess adding this path to $PATH will work,

are you sure that the normal nodejs installation add this to $PATH by default?

because I didn't use the homebrew one, I've downloaded and install it from the official site.

**Comment by olistic** [comment]
I assume you have previously installed node with Homebrew and then you decided to install it via the nodejs.org package. If that were the case, you might find the following in `/usr/local/lib/node_modules/npm/npmrc`:
```
prefix=/usr/local/Cellar/node/0.12.2_1/libexec/npm
```

which must be changed to:
```
prefix=/usr/local
```

If you change that line and reinstall the `warriorjs` package, it should work.

**Comment by oronbz** [comment]
Thanks alot man!
