### ISSUE TITLE
ES6 hints/tips for ES5 users.

### ISSUE THREAD

**Issue by KingScooty** [olistic/warriorjs#21]
Really like this concept. As someone looking to use more ES6 goodness in my code, it'd be nice to get some ES6 based hints for each level that'll help people like me start to use more ES6 concepts over ES5.

**Comment by olistic** [comment]
Sure, I will definitely write a section containing useful hints for using ES6 concepts in the game, it's a good idea! Thank you for the support. Stay tuned.

**Comment by olistic** [comment]
The [Tips & hints](https://github.com/olistic/warriorjs#tips-and-hints) section of the README is now published.
