### ISSUE TITLE
Any plans on i18n?

### ISSUE THREAD

**Issue by Songkeys** [olistic/warriorjs#228]
I've seen an `i18n` directory and a `language.js` file. But did I miss something or is there just an English version for now? If nothing, any plans on that? I think I could help contribute with some Chinese translation job to bring this to more people. Thanks.

**Comment by olistic** [comment]
Hello @Songkeys. First, thanks for your contribution offer. Now, i18n is just for the docs, available [here](https://warrior.js.org). The web version of the game doesn't currently support other languages, nor there's a plan for it in the near future.
