### ISSUE TITLE
Documentation links are broken in many places

### ISSUE THREAD

**Issue by bbugh** [olistic/warriorjs#229]
# Environment

This is the web version

# Steps to reproduce

1. Links at the bottom of the README go to the wrong link

wrong: https://warrior.js.org/docs/play/space-api <-- missing "er" on player
right: https://warrior.js.org/docs/player/space-api

wrong: https://warrior.js.org/docs/play/general-tips
right: https://warrior.js.org/docs/player/general-tips

2. Search results in the documentation go to the wrong links

Say, search for "look" and click a result. 

Wrong: https://warrior.js.org/docs/en/play/js-tips#docsNav
Correct: https://warrior.js.org/docs/en/player/js-tips

# Expected Behavior

It looks like everywhere is just missing `play` -> `player`.

**Comment by olistic** [comment]
Thanks for reporting, number 1 should be fixed now. Number two will take a bit till Algolia's crawlers pick up the new config.
