### ISSUE TITLE
get space of warrior

### ISSUE THREAD

**Issue by nylki** [olistic/warriorjs#23]
Not sure if this is possible or not. Is it possible to get the space where the warrior is currently standing?
I might want to use that location later on.

I have an idea how to emulate this: when warrior.walk() -> `let comingFrom = `  opposite of current walking direction (if walking right, save left, if walking forward, save backward) -> next turn: save `warrior.feel(comingFrom)` for later use, as this is the space the warrior came from.

**Comment by olistic** [comment]
No, it isn't. May I ask why do you want to obtain your current location? Maybe I can think on other things you can do to get the same results.
About your idea, the `comingFrom` variable should be a property of the Player object (like `this._comingFrom`). If not, you won't be able to get it value in the following turn.

**Comment by nylki** [comment]
> No, it isn't. May I ask why do you want to obtain your current location?

To mark a dangerous location (more than 2 enemies in feel range). If at any next turn I come back close there, I can check before walking there, if it is actually a dangerous location. This of course only works, if enemies are ont moving (i am at level 4 currently, so not sure if thats gonna happen).

To your second remark: I have been able to store data outside of Player that remains in memory.

**Comment by olistic** [comment]
You can store your warrior's position in an array with X and Y, starting at [0, 0], and the locations you found out to be dangerous in another array:

```javascript
class Player {
  constructor() {
    this._warriorPosition = [0, 0];
    this._dangerousLocations = [];
    // ...
  }

  // ...
}
```

Then, anytime you consider your position to be dangerous, you can push it to your `dangerousLocations` array: 

```javascript
if (this.isSurrounded(warrior)) {
  this._dangerousLocations.push(this._warriorPosition);
}
```

Of course, you'll have to update your current position each time you walk (I recommend creating an auxiliar function that receives the walking direction and returns the new position, relative to the current one).

And about storing data outside the Player class, I recommend not to do so. Depending on the way you are doing it, it can cause you problems in the epic mode, in which each level is played right after the previous one, without interruption.
