### ISSUE TITLE
access to newer abilities in previous levels

### ISSUE THREAD

**Issue by rbtbar** [olistic/warriorjs#233]
Hi, currently I taking 'baby-steps' on https://warriorjs.com. 

I've noticed that when I switch the level (via dropdown) back to "1", the list of available abilities in the readme contains all abilities gained during the game. The warrior also gets an access to them. Is it intentional?

**Comment by olistic** [comment]
Hi! It's not intentional, unless you have already completed level 9 and entered "Epic mode" (check if you have an "Epic mode" checkbox below the level dropdown). Epic mode runs your epic code from level 1 to level 9 without stop, so you have all the abilities available.

**Comment by jpparent** [comment]
Just completed baby-steps' level 9 and everything seems fine if I go back to other levels while not in Epic Mode. Toggling between Epic Mode correctly toggles between the level's original readme and the Epic Mode's one. Same thing for the underlying abilities.

**Comment by olistic** [comment]
@rbtbar This ended up being a bug, which was already fixed.

@jpparent Thanks for your report!
