### ISSUE TITLE
Connect WarriorJS CLI with warriorjs.com

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#235]
The proposal is to be able to sync your code with the online version of WarriorJS (https://warriorjs.com) so that you can play from the terminal with your own IDE, but also be part of the global leaderboard (https://warriorjs.com/leaderboard). The user will need to authenticate via the CLI, and then, after succeeding in each level, the code would be sent to the WarriorJS API (GraphQL API running at https://api.warriorjs.com/graphql) for validation and inclusion in the leaderboard.

Let me know if you're interested in working on this!

**Comment by Zorgatone** [comment]
> The proposal is to be able to sync your code with the online version of WarriorJS (https://warriorjs.com) so that you can play from the terminal with your own IDE, but also be part of the global leaderboard (https://warriorjs.com/leaderboard). The user will need to authenticate via the CLI, and then, after succeeding in each level, the code would be sent to the WarriorJS API (GraphQL API running at https://api.warriorjs.com/graphql) for validation and inclusion in the leaderboard.
> 
> Let me know if you're interested in working on this!

It would be great!

**Comment by olistic** [comment]
Closing as I don't have time to work on this at the moment.
