### ISSUE TITLE
Add ability to get warrior's max health

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#237]
The proposal is to add a `.maxHealth()` ability (sense), that allows the player to get the warrior's max health programmatically, so hardcoding its value in the code is no longer necessary.

**Comment by olistic** [comment]
@JSeed Of course! Let me know if you need any help while at it.

**Comment by enrique-ramirez** [comment]
I didn't know this was open source! Thanks for the quick response. I'll try to help out soon as well!
