### ISSUE TITLE
Make senses less powerfull

### ISSUE THREAD

**Issue by Aradiv** [olistic/warriorjs#24]
With the current warrior.listen() you can forget about all the other senses.
Just call warrior.listen() once at the beginning of the Level and you never have to use any senses again.

In my Opinion only the ticking captives/enemys? should be returned by listen. Other units remain silent.
This way you have to Look arround. 
But but how about you can only determin the base class of the enemy with warrior.look() 
(Ranged/Melee/Captive)

This way you have to use all senses to determine the right Behavior.

New Senses in summary
listen - only return tickings
look - only return baseclass
feel - return detail Information

**Comment by olistic** [comment]
Hello @Aradiv, I'm closing old issues to create a fresh backlog for the project. I'll evaluate your issue and consider adding it to the backlog. Thanks!
