### ISSUE TITLE
Must The Warrior received bonus damage when he has been attacked by enemies from 'backward'?

### ISSUE THREAD

**Issue by dandgerson** [olistic/warriorjs#245]
Hello, WarriorJS!

When the Warrior have being attacked from 'backward' he has recieved normal damage.
But I think, that it is logical true, when the warrior have receive damage from 'backward', ***he must be more vulnerable***. But it's about of the balance of the game, and so I can't offer right pull request with my novice programming skills, but i with much pleasure learn, how it's can be perform.

If you agree with this one, and if you'll having commit with this feature, please inform me.

**Comment by olistic** [comment]
Closing as I don't have time to work on this now. Feel free to reopen if you want to grab this.
