### ISSUE TITLE
Add retro sounds

### ISSUE THREAD

**Issue by entrptaher** [olistic/warriorjs#252]
The original ruby warrior from 2012 had sound effects so it made everything more enjoyable and interactive. https://www.bloc.io/ruby-warrior

That server is dead but the client is still online. What's our plan to add sounds in warriorJS?

**Comment by olistic** [comment]
I'm open to the idea of sounds, yeah. At least adding ambience music like in ruby-warrior should be pretty easy. Any recommendation?

**Comment by olistic** [comment]
Closing as I don't have time to work on this at the moment.
