### ISSUE TITLE
This code is wierdly running

### ISSUE THREAD

**Issue by pickle69420** [olistic/warriorjs#263]
Sorry for bugging you, but is it just me or is this code supposed to work?

# Environment

The warriorjs website.

# Steps to reproduce

Use this code on the website level 6 (playTurn function):

```javascript
if (warrior.feel('backward').isEmpty()) {
    warrior.walk('backward');
} else if (warrior.feel('backward').getUnit().isEnemy()) {
  //Other code (unrelated)
} else if (warrior.feel('backward').getUnit().isBound()) {
  warrior.rescue('backward');
} else if (warrior.feel('backward').isWall()) {
  this.checkedback = true;
}
```

It will give a wierd error about getUnit being undefined

In the docs it says that if getUnit is undefined then there is nothing hence isEmpty should be true but the else if runs so i dont know what is happening.

If you use this code though:

```javascript
if (warrior.feel('backward').getUnit() === undefined) {
    warrior.walk('backward');
} else if (warrior.feel('backward').getUnit().isEnemy()) {
  //Other code (unrelated)
} else if (warrior.feel('backward').getUnit().isBound()) {
  warrior.rescue('backward');
} else if (warrior.feel('backward').isWall()) {
  this.checkedback = true;
}
```
It works but isWall() still returns false so my player keeps bumping into wall.

# Expected Behavior

isWall and isEmpty should work...

# Actual Behavior

It is wierd (maybe my mistake)

**Comment by tepinly** [comment]
The game's dead, check the previous issues that have been up for months discussing the same bug with no response whatsoever.

**Comment by pickle69420** [comment]
So sad

**Comment by olistic** [comment]
> It will give a wierd error about getUnit being undefined

A space is empty if you can walk there ([either no other unit occupying the space or no wall](https://github.com/olistic/warriorjs/blob/ec531b4d4b6b7c3e51e5adbd03f575af56ebebc8/packages/warriorjs-core/src/Space.js#L90-L97)). If there's a wall, `isEmpty()` will be `false` but `getUnit()` will be `undefined`.

You should check if you have a unit in the space (`getUnit() !== undefined`) before calling methods on the unit. Or check if there's no wall first.

**Comment by olistic** [comment]
> The game's dead, check the previous issues that have been up for months discussing the same bug with no response whatsoever.

The game is not dead - I just don't have time to be as active anymore, and I'm relying more in the community members that want to help.
