### ISSUE TITLE
No option to delete accounts

### ISSUE THREAD

**Issue by sociablerobot10** [olistic/warriorjs#267]
There are no ways to delete accounts to give users an option to have their data deleted.

**Comment by olistic** [comment]
Yes, sorry, I'm not actively maintaining this project anymore. But if you want your account deleted, you can email me and I'll delete it for you.

**Comment by olistic** [comment]
[moliverafreire@gmail.com](mailto:moliverafreire@gmail.com) (it's in my GitHub profile)

**Comment by olistic** [comment]
Yes, deleted.
