### ISSUE TITLE
player proxy of Space does not include method getDirectionOf

### ISSUE THREAD

**Issue by amorphous1** [olistic/warriorjs#28]
I started warriorjs in intermediate difficulty and am stuck in level 4 when trying to free the two captives. 

```javascript
let captiveSpace = warrior.listen().find(space => space.isCaptive());
console.log(captiveSpace);
console.log(warrior.directionOf(captiveSpace));
```
The last line in the test code above fails with
```
TypeError: Object [object Object] has no method 'getLocation'
    at Position.getDirectionOf (/usr/lib/node_modules/warriorjs/lib/Position.js:107:39)
```

If I read the source correctly, the `listen()` call converts the spaces to "player objects" before returning them, which drops the method `getLocation()`. But `getLocation()` is needed for `warrior.directionOf()`.

If I'm just using it wrong, please consider making the level's README a bit more clear instead.

**Comment by olistic** [comment]
@amorphous1 Thank you for spotting this, the solution is already in progress.
