### ISSUE TITLE
Make speed configurable

### ISSUE THREAD

**Issue by flipace** [olistic/warriorjs#30]
It would be great if there were an option to make the speed of the terminal output configurable.

I couldn't find anything in the readme and it seems like the delay is hardcoded at the moment.
Any chance to make this configurable?

**Comment by olistic** [comment]
You can configure the speed by using the -t option, followed by the time in seconds. The default is 0.6 seconds.

```$ warriorjs -t 0.3```

**Comment by flipace** [comment]
thx!

**Comment by rista404** [comment]
Would be great if you could put that option in the README :)

**Comment by olistic** [comment]
I added a note in the Usage section about the CLI options.
