### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by pawel2105** [olistic/warriorjs#31]
I've tried installing this but can't get it to work:

```
mkdir javascript
cd javascript 
npm install -g warriorjs
```

But then running it doesn't recognize the command:

```
  $ warriorjs
  > -bash: warriorjs: command not found
```

**Comment by olistic** [comment]
Please take a look at #2. Let me know if it solves the issue and I'll close this.

**Comment by pawel2105** [comment]
@olistic that was my problem :)
