### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by edsil** [olistic/warriorjs#35]
I didn't have node.js installed on my machine, so obviously the command to install the package didn't work and I spent a good amount of time to finally understand that I needed node.js. I suggest adding a note to the installation notes about having node.js installed.
Thanks.

**Comment by edsil** [comment]
I (seem) to have installed it but I am not able to run it. This is what I've tried:

bash-3.2$ sudo npm install -f warriorjs
npm WARN using --force I sure hope you know what you are doing.
warriorjs@2.2.0 node_modules/warriorjs
├── bluebird@3.4.1
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, rimraf@2.5.3, klaw@1.3.0, jsonfile@2.3.1, graceful-fs@4.1.4)
├── ejs@2.4.2
├── glob@7.0.5 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.5, minimatch@3.0.2)
├── yargs@4.7.1 (decamelize@1.2.0, y18n@3.2.1, camelcase@3.0.0, set-blocking@1.0.0, window-size@0.2.0, require-main-filename@1.0.1, lodash.assign@4.0.9, yargs-parser@2.4.0, cliui@3.2.0, string-width@1.0.1, os-locale@1.4.0, pkg-conf@1.1.3, read-pkg-up@1.0.1)
├── inquirer@0.12.0 (ansi-regex@2.0.0, strip-ansi@3.0.1, ansi-escapes@1.4.0, rx-lite@3.1.2, through@2.3.8, cli-width@2.1.0, figures@1.7.0, string-width@1.0.1, readline2@1.0.1, cli-cursor@1.0.2, run-async@0.1.0, lodash@4.13.1)
└── warriorjs-engine@0.10.2 (lodash.range@3.1.5, lodash.isequal@4.2.0, lodash.startcase@4.2.1, lodash.camelcase@4.1.1, lodash.uniqby@4.5.0, babel-polyfill@6.9.1, babel-core@6.10.4, babel-preset-es2015@6.9.0, babel-preset-stage-0@6.5.0)
bash-3.2$ cd bin
bash-3.2$ bash warriorjs
warriorjs: line 3: syntax error near unexpected token `('
warriorjs: line 3: `const Runner = require('../lib/Runner').default;'
bash-3.2$

**Comment by olistic** [comment]
I will add that to the installation notes, thanks.

Regarding the issue you're having, try to install the module globally with the -g option, not -f:

```bash
$ npm install -g warriorjs
```

Then, you should be able to play the game just by executing `warriorjs` from any directory.

**Comment by edsil** [comment]
Fantastic! Thank you very much, it has worked like a charm :-)
