### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by simonwulf** [olistic/warriorjs#36]
When an error occurs, it would be super useful to know what line it occurred on etc.

Love the game!

**Comment by everystone** [comment]
This is a must have, especially for people new to javascript.

**Comment by ericperez** [comment]
Right now when you have an error in the code the output simply says "Invalid submitted code. Check the syntax and try again."

Adding line numbers/columns where the issue(s) are would could be easily accomplished by running eslint on Player.js if there is a problem and would be a lot more helpful than the current output. Thoughts?

**Comment by olistic** [comment]
@simonwulf @everystone @ericperez This is now part of the new `@warriorjs/cli`. Closing now.
