### ISSUE TITLE
Import classes from other files?

### ISSUE THREAD

**Issue by everystone** [olistic/warriorjs#39]
Is import not supported in Player.js?

`import { MyClass } from './class.js'` results in `Cannot read property playTurn of null`

Have anyone found a workaround? Great game btw!

**Comment by olistic** [comment]
Hello @everystone, I'm closing old issues to create a fresh backlog for the project. I'll evaluate your issue and consider adding it to the backlog. Thanks!

**Comment by JayAndCatchFire** [comment]
@olistic I also ran into this one.  It would be nice to be able to split up my code into units that make a little more sense, maybe with `.mjs` Node modules.  Do you want me (or @everystone) to open a new ticket for this?

**Comment by olistic** [comment]
Hello @JayAndCatchFire, thanks for your interest in the project. Yeah, go for it! I'm open to receive a PR that adds that capability. Thanks again.
