### ISSUE TITLE
Suggestion: add solutions

### ISSUE THREAD

**Issue by skillzzjesse** [olistic/warriorjs#40]
I think you should create a page where you list all the solutions for each level. 

> In your readme you say _"This is a game designed to teach JavaScript and artificial intelligence in a fun, interactive way."_ 

Since this game is about learning I think you should be able to learn from your mistakes. I found myself stuck on a level and didn't know what to do.

I think being able to view the solution after you tried your best to solve it yourself helps you create better code, you gain good insight into how the code _should_ look and with this example in mind you can go ahead and tackle the next level.

 You can go about this a couple of different ways, you can for instance create something like a wiki page where you just list them all (this can also be right here on github (just a bunch of files)). 
You can also include the solution inside the level's folder, or include a folder with solutions on the users side of things. 

I really hope you'll add this feature in the future! Awesome project!

**Comment by olistic** [comment]
Hey, thanks for the suggestion. It's in my plans to create a landing site for the project and when I do, I will include solutions there.

**Comment by skillzzjesse** [comment]
Cool! Looking forward to it! 

Awesome project! Very good way to learn!
