### ISSUE TITLE
Free Ability - "Say" or "Think"

### ISSUE THREAD

**Issue by jproffitt3ge** [olistic/warriorjs#41]
I found myself needing to determine when my warrior changed states, and realized there is no api for showing that in the flow of the simulation.

It would be nice if there was an ability that showed a message like: <Player> thinks "Hello World!" in line with the turns, just like any other action.

**Comment by olistic** [comment]
Hey, I like it! It'd have to be a `Sense` rather than an `Action`, because senses are free. So I think that "Think" is the best choice.

Would you like to submit a PR to [warriorjs-engine](https://github.com/olistic/warriorjs-engine)?

**Comment by olistic** [comment]
Hello @jproffitt3ge, I'm closing old issues to create a fresh backlog for the project. I'll evaluate your issue and consider adding it to the backlog. Thanks!
