### ISSUE TITLE
Should i build a class "warrior"?

### ISSUE THREAD

**Issue by stlinjs** [olistic/warriorjs#43]
here is my code
class Player {
    playTurn(warrior) {
        // Cool code goes here
        if (warrior.feel().isEnemy()) {
            warrior.attack();
        } else {
            warrior.walk();
        }
    }
}

The system told me " warrior.feel is not a function" after  running command "warriorjs" , so should i build a class "warrior"?

**Comment by olistic** [comment]
Hello @stlinjs! What level is your warrior in? If it's level 1, `feel` (and `attack`) will not be available. Look at the README for that specific level :)

**Comment by stlinjs** [comment]
Thanks for your reply! I'm in level 5 now . The program is getting more and more complex. Cause i  learn few about AI , could you tell me how to do it? How to make my own AI program ? I can not understand it in the game.
