### ISSUE TITLE
i beg you please tell how to run the project i want to see output

### ISSUE THREAD

**Issue by BrandedAlok** [olistic/warriorjs#44]
i beg you please tell how to run the project i want to see output

**Comment by olistic** [comment]
1. Install Node.js if you don't have it already (you can do this from [nodejs.org](https://nodejs.org/))
2. Install WarriorJS: in the terminal, type `npm install -g warriorjs` and hit Enter
3. Run WarriorJS: in the terminal, type `warriorjs` and hit Enter

I'm closing this issue now, feel free to reopen if the previous steps don't work for you.
