### ISSUE TITLE
Add warrior score next to its health when printing the play log

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#48]
It could be a good addition to see the current score of the warrior in the play log. Example:

```
--------------------------------------- turn 005 ---------------------------------------
♥ 14
⬥ 0
╔════════╗
║   @s  >║
╚════════╝
> Spartacus attacks forward and hits Sludge
> Sludge takes 5 damage, 2 health power left
> Sludge attacks forward and hits Spartacus
> Spartacus takes 3 damage, 14 health power left
--------------------------------------- turn 006 ---------------------------------------
♥ 14
⬥ 12
╔════════╗
║   @   >║
╚════════╝
> Spartacus attacks forward and hits Sludge
> Sludge takes 5 damage, 0 health power left
> Sludge dies
> Spartacus earns 12 points
--------------------------------------- turn 007 ---------------------------------------
♥ 14
⬥ 12
╔════════╗
║    @  >║
╚════════╝
> Spartacus walks forward
```

To make that possible, the core will need to include the unit's score along with the currently included fields.

**Comment by RascalTwo** [comment]
What color would you like the score line to be?

![bright-yellow-warrior-score](https://user-images.githubusercontent.com/9403665/39899666-3f504bd8-548b-11e8-8fae-2c1e68c06fdf.png)

Bright Yellow looks good to me.

**Comment by olistic** [comment]
I like it! My only concern is that it looks like if it was more important than the health... Maybe regular yellow, or making the health bright red?

**Comment by RascalTwo** [comment]
Regular yellow is already being used, see the captive being unbound. Figured you wanted to have as many elements uniquely coloured.

*****

Having the health bright red should be better, I'll make the PR tomorrow.

**Comment by RascalTwo** [comment]
The bright red looks perfect.

*****

I only added `score` to the `.toJSON()` method of the `Warrior`, since - for now at least - only the `Warrior` needs it's `score` at the moment.

*****

I think the only documentation that needs updating due to the change is the Preview `.gif`. on the `README.md`

If you could tell me what color scheme is being used, I can update it. (I'm also a user of VSCode)

Or, another issue could be created to have the `.gif` updated at a later date, up to you.

**Comment by olistic** [comment]
Thanks @RascalTwo!

> I think the only documentation that needs updating due to the change is the Preview `.gif`. on the `README.md`

Good call. Don't worry about it, I will update it later! (The color scheme is Nord, if you're still curious.)

**Comment by olistic** [comment]
@RascalTwo I'm going to update the GIF later, but I already added a screenshot to the [homepage](https://warrior.js.org) that shows your change!
