### ISSUE TITLE
Run code on every new level

### ISSUE THREAD

**Issue by Kamahl19** [olistic/warriorjs#5]
Hi, 

how can I run some sort of config code to set some defaults on the begging of every level? When I run levels separately, I simple check if var is undefined however if I play an epic mode, it runs the config only once in 1st level. 

Thanks

**Comment by olistic** [comment]
Hello, could you please give an example of what you want to achieve, or how you are doing it actually?

**Comment by Kamahl19** [comment]
Thanks for quick reply. 

Well at the beginning of each level, I would like to find out which wall is closer, left or right. I also want to set the _health to 20 so that it does not use the value from previous level. I also want to set if we already hit wall in this level etc..

**Comment by Kamahl19** [comment]
Here is my first version of AI for beginner levels http://pastebin.com/ChPCXnaJ As you can see I have a _setConfig method which I want to call at the beginning of each level.

**Comment by olistic** [comment]
I don't know were you were putting your config logic before, but I think using a constructor for your warrior will fulfill your needs. Something like this:

```javascript
class Player {
  constructor() {
    this._health = 20;
    this._hasHitWall = false;
  }

  playTurn(warrior) {
    // Cool code
  }
}
```

The Player `constructor` will be executed at the beginning of each level, even in Epic mode.

**Comment by olistic** [comment]
And don't use globals! With instance properties you'll be fine :)

**Comment by Kamahl19** [comment]
Yea I am just replacing the globals :) Ok thanks for the idea. Also can I somehow access warrior in constructor?

**Comment by olistic** [comment]
Not directly, but this came to my mind that might solve whatever you want to do with the warrior:

```javascript
class Player {
  constructor() {
    this._isFirstTurn = true;
  }

  playTurn(warrior) {
    if (this._isFirstTurn) {
      // Do whatever you want with warrior
      this._isFirstTurn = false;
    }
  }
}
```

It might be ugly but may do the trick ;)

**Comment by Kamahl19** [comment]
Yea I just did that but wanted a cleaner solution :) Thanks a lot for quick responses

**Comment by Kamahl19** [comment]
Dont you plan to deploy this online and let users create their AIs in online editors and then submitting them and compeating with each other?

**Comment by Kamahl19** [comment]
Maybe also let users create new levels to test AIs properly with much more levels. Or generate levels randomly so that AIs cant be created just for known levels but are generally working in whatever level.

**Comment by olistic** [comment]
Yes, deploying a web version of the game is in the roadmap. I encourage you to open new issues with ideas. I'll close this to keep it neat.

Thank you for the support!
