### ISSUE TITLE
Array instead of string from look()

### ISSUE THREAD

**Issue by jdarling** [olistic/warriorjs#6]
Ok, so I didn't completely follow the directions and did a git clone of warriorjs and that means I probably have work in progress code.  Admitted :)

Now that we are on the same page, I've worked through differences easily enough in the code, until I got to the part where I have to start looking for wizards (level 8).  Problem is, seems in the next version look() is going to return a list of objects instead of a string representation of what's in the direction your "looking"

Any pointers, I've tried inspecting the result but its a bit less than conducive to understanding.

I can post my code, but I doubt it will change anything :)

**Comment by olistic** [comment]
I'm not quite sure I understand your concern. The `look` ability is returning an array of Spaces, not a string representation, and you can call any `Space` method on them... Please correct me if I misunderstood you.

**Comment by jdarling** [comment]
I'll try it this way, what is the prototype for Space?  What methods, properties, etc are available on it for use?

Basic types should be documented somewhere, but I can't find it.  Initially I misread the readme for level 8 and thought look was supposed to return a string of characters (made sense) now I get the array of objects but no clue how to interact with them.

**Comment by jdarling** [comment]
I'm guessing the answer is "Read the source" now that I think about it that makes sense, but I took it as everything you needed to know was in the README for each level.

**Comment by olistic** [comment]
I wrote the WarriorJS wiki, where you'll have all the info needed to complete each level. Particularly, [here](https://github.com/olistic/warriorjs/wiki/Methods) is the list of methods you can call on a `Space`. I'll put a mention to it in the README of the repo. Thanks!

**Comment by jdarling** [comment]
Thanks, not sure how I missed that :(

Really enjoy WarriorJS been a fun little exerciser and learned some new techniques even though I already use ES6 (with 6to5 and React) almost every day.
