### ISSUE TITLE
Rescue ability awards unit's reward

### ISSUE THREAD

**Issue by olistic** [olistic/warriorjs#64]
The [rescue ability awards a fixed amount of points](https://github.com/olistic/warriorjs/blob/6b90d0629e563ea664e822acf3914353c99c5a7c/packages/warriorjs-abilities/src/rescue.js#L17) for rescuing a captive unit. With the addition of the reward field, it should give those points now instead of the fixed amount.

Blockers: #60

**Comment by RascalTwo** [comment]
Quite a small PR, just a couple lines of code and documentation updated.

Allows level designers to make captives more or less valuable, giving the player a possible choice between risk and reward.
