### ISSUE TITLE
`warrior.feel()` exposes floor object

### ISSUE THREAD

**Issue by nloomans** [olistic/warriorjs#71]
# Environment

## System:
 - OS: Linux 4.13 Linux Mint 18.3 (Sylvia)
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 230.82 MB / 7.68 GB
 - Container: Yes
 - Shell: 5.1.1 - /usr/bin/zsh
## Binaries:
 - Node: 10.1.0 - /usr/bin/node
 - Yarn: 1.6.0 - /usr/bin/yarn
 - npm: 5.6.0 - /usr/bin/npm

**Note:** I manually replaced `npm` with `yarn` in the command.

# Steps to reproduce

1. Replace the following line to `@warriorjs/core/lib/PlayerLoader.js` **for demonstration purposes**:

```diff
-this.sandbox = vm.createContext();
+this.sandbox = vm.createContext({ console });
```

2. Execute `console.log(warrior.feel().floor);` in a level that has `warrior.feel()` available.

# Expected Behavior

`floor` should not be accesible

# Actual Behavior

The following gets logged into the console:

```
Floor {
  width: 7,
  height: 1,
  stairsLocation: [ 6, 0 ],
  units:
   [ Warrior {
       name: 'mrCyborg',
       character: '@',
       maxHealth: 20,
       captive: false,
       abilities: [Map],
       effects: Map {},
       health: 20,
       position: [Position],
       bound: false,
       score: 0,
       turn: [Turn],
       player: [Player] },
     Unit {
       name: 'Thick Sludge',
       character: 'S',
       maxHealth: 24,
       captive: false,
       abilities: [Map],
       effects: Map {},
       health: 24,
       position: [Position],
       bound: false,
       score: 0,
       turn: null,
       playTurn: [Function: playTurn] },
     Unit {
       name: 'Archer',
       character: 'a',
       maxHealth: 7,
       captive: false,
       abilities: [Map],
       effects: Map {},
       health: 7,
       position: [Position],
       bound: false,
       score: 0,
       turn: null,
       playTurn: [Function: playTurn] },
     Unit {
       name: 'Thick Sludge',
       character: 'S',
       maxHealth: 24,
       captive: false,
       abilities: [Map],
       effects: Map {},
       health: 24,
       position: [Position],
       bound: false,
       score: 0,
       turn: null,
       playTurn: [Function: playTurn] } ],
  warrior:
   Warrior {
     name: 'mrCyborg',
     character: '@',
     maxHealth: 20,
     captive: false,
     abilities:
      Map {
        'walk' => [Object],
        'attack' => [Object],
        'feel' => [Object],
        'health' => [Object],
        'rest' => [Object] },
     effects: Map {},
     health: 20,
     position: Position { floor: [Circular], location: [Array], orientation:'east' },
     bound: false,
     score: 0,
     turn: Turn { action: null },
     player: Player { turn: 1, history: [Object], warrior: [Turn] } } }
```

**Comment by nloomans** [comment]
This will probably become an issue if #69 gets fixed. Since players can then easily discover this object.

**Comment by olistic** [comment]
Hello @nloomans, thanks for the report. This is a known issue that was already fixed prior to the big refactor I recently made (see #26). I didn't cherry-pick those changes intentionally because I wanted to explore other ways of fixing this (maybe simpler/more elegant), e.g. Symbols for "private" properties. Let me put some additional thought on this, suggestions are also welcome.

**Comment by nloomans** [comment]
Thanks! Symbols seem like a good solution. I did a few test and it should be noted that, while symbols are not accessible in the vm context, their content can still be printed using `console.log`. `JSON.stringify`, however, doesn't print symbols.

**Comment by olistic** [comment]
@nloomans I opened a PR with a fix for this, just letting you know in case you're curious. 

Symbols ended up not being a good solution for this, because one could still access the "private" members by using [`Object.getOwnPropertySymbols`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols).
