### ISSUE TITLE
How to Get Past Level Four?

### ISSUE THREAD

**Issue by DevGuy128** [olistic/warriorjs#9]
Great program, but I am having a hard time getting past level four on beginner mode. Could you please help?

**Comment by olistic** [comment]
To get past level four is crucial that your warrior rest, just like in level three. However, now you must check that you are not being attacked before resting. You should store your health in a Player's instance property at the end of each turn, and if your warrior is injured but the health at the end of past turn is greater than its current health, you should walk/attack instead of rest.

**Comment by DevGuy128** [comment]
I've been trying to do that, but I can't figure out what the code for it would be.

**Comment by olistic** [comment]
I could give you a few pointers, but not the complete solution. After all, this game is intended to learn, and you won't learn anything if I do.

```javascript
class Player {
  constructor() {
    this._health = 20;
  }

  playTurn(warrior) {
    // TODO: Add missing condition
    if () {
      warrior.rest();
    } else {
      if (warrior.feel().isEnemy()) {
        warrior.attack();
      } else {
        warrior.walk();
      }
    }

    // TODO: Update this._health with warrior.health
  }

  isInjured(warrior) {
    // TODO: Return false if warrior health is less than 20
  }

  isUnderAttack(warrior) {
    // TODO: Compare this._health with warrior.health()
  }
}
```

You can call the newly defined methods `isInjured` and `isUnderAttack` (and any other method you create in the future) from the `playTurn` method like this:

```javascript
this.isInjured(warrior);
```

Good luck!

**Comment by DevGuy128** [comment]
Thanks!

**Comment by pawel2105** [comment]
My JS ain't that good, although I'm pretty sure I'm on the right track. I've added my code to [this gist](https://gist.github.com/pawel2105/fa6c10a285890ce90b2215274fdc4a09) so as not to spoil for anyone. Would appreciate some guidance via a tip in the gist (do gist comments send notifications?)

**Comment by olistic** [comment]
@pawel2105 I just left a comment in your gist. Good luck!

**Comment by williamgurney** [comment]
@olistic Hi, really enjoy the game however struggling with the above.
Everything goes okay however my warrior does not rest enough to beat the final sludge, he will rest for one turn then walk the other!

Would appreciate some guidance if possible? It feels like such a small thing.
`
class Player {
  constructor() {
    this._health = 20;
  }
  playTurn(warrior) {
    if (this.isInjured(warrior) === true && this.isUnderAttack(warrior) === false) {
      warrior.rest();
    } else {
      if (warrior.feel().isEnemy()) {
      warrior.attack();
    } else {
      warrior.walk();
    }
}
this._health = warrior.health();
}

  isInjured(warrior) {
    if (warrior.health() < 20) {
      return true;
    } else {
      return false;
    }
  }
  isUnderAttack(warrior) {
    if (this._health !== warrior.health()) {
      return true;
    } else {
        return false;
    }
  }
}
`

**Comment by olistic** [comment]
Hi @williamgurney! I left a [comment](https://gist.github.com/williamgurney/080809c689fbf5f7b848a859c0bb8a17#gistcomment-2588101) in your gist, cheers!

**Comment by TomsH1** [comment]
class Player {
  
  constructor() {
    this._health = 20;
  }

  playTurn(warrior) {
    // TODO: Add missing condition
    warrior.think("Am I under attack? "+this.isUnderAttack(warrior.health()));
    if (
      this.isInjured(warrior.health()) && 
      !this.isUnderAttack(warrior.health())) {
      warrior.rest();
    } else if(!warrior.feel().isEmpty()) {
      warrior.attack();
    } else {
      warrior.walk();
    }
    
    this._health = warrior.health(); 
  }

  isInjured(health) {
    if(health < 20){
      return true;
    }
    return false;
    // TODO: Return true if warrior health is less than 20
  }

  isUnderAttack(health) {
    if(health < this._health){
      return true;
    }
    return false;
    // TODO: Compare this._health with warrior.health()
  }
}

Based on your example this implementation works. Try creating a method chained IsEnemy() to feel(), but doing a !warrior.feel().isEmpty() is enough

**Comment by TomsH1** [comment]
```
class Player {
  
  constructor() {
    this._health = 20;
  }

  playTurn(warrior) {
    // TODO: Add missing condition
    warrior.think("Am I under attack? "+this.isUnderAttack(warrior.health()));
    if (
      this.isInjured(warrior.health()) && 
      !this.isUnderAttack(warrior.health())) {
      warrior.rest();
    } else if(!warrior.feel().isEmpty()) {
      warrior.attack();
    } else {
      warrior.walk();
    }
    
    this._health = warrior.health(); 
  }

  isInjured(health) {
    if(health < 20){
      return true;
    }
    return false;
    // TODO: Return true if warrior health is less than 20
  }

  isUnderAttack(health) {
    if(health < this._health){
      return true;
    }
    return false;
    // TODO: Compare this._health with warrior.health()
  }

}

```
@olistic Based on your example this implementation works. I tried creating a method chained IsEnemy() to feel(), but doing a !warrior.feel().isEmpty() is enough

**Comment by Winder777** [comment]
No es muy creativa mi respuesta, pero es otra alternativa:

class Player {

  playTurn(warrior) {
    
    if (this.health==null){this.health=0;} 

if (this.health==0) {warrior.walk()}
else if(this.health<=5){warrior.attack()}
else if(this.health<=6){warrior.walk()}
else if(this.health<=10){warrior.attack()}
else if(this.health<=20){warrior.rest()}
else if(this.health<=22){warrior.walk()}
else if(this.health<=30){warrior.attack()}
else if(this.health<=35){warrior.walk()}

this.health = this.health+1
warrior.think(this.health);
    }
}
