### ISSUE TITLE
Consider changing the default directory name

### ISSUE THREAD

**Issue by phil-r** [olistic/warriorjs#95]
Some people have [`AUTO_CD` or `AUTOCD`](http://zsh.sourceforge.net/Doc/Release/Options.html) set (afaik it's set by default in [`Oh My Zsh`](http://ohmyz.sh/)), therefore after after running `warriorjs` for the first time every next `warriorjs` call is the same as `cd warriorjs`.

P.S. I know about `--directory` option but anyway, maybe it will be better to change default dir name 😳.

**Comment by olistic** [comment]
Hey @phil-r! Yup, I'm aware of that (I have that option enabled myself 😂). However, I think the current names are the ones that make the most sense (both binary and directory) and I don't think this is big enough to motivate a change (specially with `--directory` in place and the possibility to [start the game from a profile directory](https://warrior.js.org/docs/en/cli-tips.html)).

I'm closing this for now as there is no action to be taken, but I'm open to ideas or suggestions.
